use_default_settings:
  engines:
    remove:
      - qwant
      - qwant news
      - qwant images
      - qwant videos
      - duckduckgo
      - duckduckgo images
      - duckduckgo videos
      - duckduckgo news
      - duckduckgo weather
      - startpage
      - startpage news
      - startpage images

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "${SEARXNG_SECRET_KEY}"
  limiter: false
  image_proxy: true

valkey:
  url: valkey://searxng-valkey:6379/0

search:
  safe_search: 1
  autocomplete: ""
  formats:
    - html
    - json
