#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shlex
from pathlib import Path
from typing import Any

import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined

from validate_models import ROOT, load_yaml, validate


GENERATED_HEADER = "# DO NOT EDIT: generated by scripts/render.py from stack.yml and models.yml"
GENERATED_VLLM_LAUNCH_DIR = ROOT / "generated/vllm-launch"


def write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def dump_yaml(value: Any, indent: int = 0) -> str:
    text = yaml.safe_dump(value, sort_keys=False, default_flow_style=False).rstrip()
    if indent:
        prefix = " " * indent
        text = "\n".join(prefix + line if line else line for line in text.splitlines())
    return text


def to_json(value: Any) -> str:
    return json.dumps(value)


def remote_chat_template(path: str) -> str:
    return "/workspace/vllm/" + path


def bool_flag(command: list[str], enabled: bool, flag: str) -> None:
    if enabled:
        command.append(flag)


def value_flag(command: list[str], value: Any, flag: str) -> None:
    if value is not None:
        command.extend([flag, str(value)])


def json_value_flag(command: list[str], value: Any, flag: str) -> None:
    if value is None:
        return
    if isinstance(value, (dict, list)):
        value = json.dumps(value, separators=(",", ":"))
    command.extend([flag, str(value)])


def engine_arg_flag(name: str) -> str:
    normalized = name.strip()
    if not normalized:
        raise ValueError("engine argument names must be non-empty")
    normalized = normalized[2:] if normalized.startswith("--") else normalized
    return "--" + normalized.replace("_", "-")


def append_engine_args(command: list[str], engine_args: dict[str, Any]) -> None:
    for name, value in engine_args.items():
        if value is None or value is False:
            continue

        flag = engine_arg_flag(str(name))
        if value is True:
            command.append(flag)
            continue

        if isinstance(value, (dict, list)):
            value = json.dumps(value, separators=(",", ":"))
        command.extend([flag, str(value)])


def normalize_startup_mods(vllm: dict[str, Any]) -> list[dict[str, str]]:
    normalized: list[dict[str, str]] = []
    for index, mod in enumerate(vllm.get("startup_mods", []) or []):
        if isinstance(mod, dict):
            host_path = str(mod["host_path"])
            container_path = str(
                mod.get("container_path")
                or f"/workspace/vllm-startup-mods/{index}-{Path(host_path).name}"
            )
        else:
            host_path = str(mod)
            container_path = f"/workspace/vllm-startup-mods/{index}-{Path(host_path).name}"
        normalized.append({"host_path": host_path, "container_path": container_path})
    return normalized


def wrap_with_startup_mods(
    command: list[str], startup_mods: list[dict[str, str]]
) -> list[str]:
    if not startup_mods:
        return command
    mod_paths = " ".join(shlex.quote(mod["container_path"]) for mod in startup_mods)
    script = (
        "set -euo pipefail; "
        f"for mod in {mod_paths}; do "
        'export WORKSPACE_DIR=/workspace/vllm; cd "$$mod"; bash run.sh; '
        "done; "
        f"cd /workspace/vllm; exec {shlex.join(command)}"
    )
    return ["bash", "-lc", script]


def build_vllm_command(model: dict[str, Any], wrap_startup: bool = True) -> list[str]:
    routing = model["routing"]
    gpu = model["gpu"]
    vllm = model.get("vllm", {})

    command = [
        "vllm",
        "serve",
        str(model["hf_model"]),
        "--host",
        "0.0.0.0",
        "--port",
        str(routing.get("internal_port", 8000)),
        "--gpu-memory-utilization",
        str(gpu["memory_fraction"]),
    ]

    served_names = model.get("served_names") or []
    if served_names:
        command.append("--served-model-name")
        command.extend(str(name) for name in served_names)

    value_flag(command, vllm.get("runner"), "--runner")
    value_flag(command, vllm.get("convert"), "--convert")
    value_flag(command, vllm.get("task"), "--task")
    value_flag(command, vllm.get("tokenizer"), "--tokenizer")
    value_flag(command, vllm.get("tokenizer_mode"), "--tokenizer-mode")
    value_flag(command, vllm.get("max_model_len"), "--max-model-len")
    value_flag(command, vllm.get("max_num_seqs"), "--max-num-seqs")
    value_flag(command, vllm.get("max_num_batched_tokens"), "--max-num-batched-tokens")
    value_flag(command, vllm.get("tensor_parallel_size"), "--tensor-parallel-size")
    value_flag(command, vllm.get("pipeline_parallel_size"), "--pipeline-parallel-size")
    value_flag(command, vllm.get("dtype"), "--dtype")
    value_flag(command, vllm.get("kv_cache_dtype"), "--kv-cache-dtype")
    value_flag(command, vllm.get("kv_cache_memory_bytes"), "--kv-cache-memory-bytes")
    value_flag(command, vllm.get("load_format"), "--load-format")
    value_flag(command, vllm.get("quantization"), "--quantization")
    value_flag(command, vllm.get("attention_backend"), "--attention-backend")
    value_flag(command, vllm.get("tool_call_parser"), "--tool-call-parser")
    value_flag(command, vllm.get("reasoning_parser"), "--reasoning-parser")
    value_flag(command, vllm.get("generation_config"), "--generation-config")
    value_flag(command, vllm.get("revision"), "--revision")
    value_flag(command, vllm.get("code_revision"), "--code-revision")
    value_flag(command, vllm.get("tokenizer_revision"), "--tokenizer-revision")
    json_value_flag(command, vllm.get("hf_overrides"), "--hf-overrides")
    json_value_flag(command, vllm.get("mm_processor_kwargs"), "--mm-processor-kwargs")
    json_value_flag(command, vllm.get("pooler_config"), "--pooler-config")
    json_value_flag(command, vllm.get("speculative_config"), "--speculative-config")
    json_value_flag(command, vllm.get("diffusion_config"), "--diffusion-config")
    json_value_flag(
        command, vllm.get("override_generation_config"), "--override-generation-config"
    )
    json_value_flag(
        command,
        vllm.get("default_chat_template_kwargs"),
        "--default-chat-template-kwargs",
    )

    chat_template = vllm.get("chat_template")
    if chat_template:
        value_flag(command, remote_chat_template(str(chat_template)), "--chat-template")

    bool_flag(command, bool(vllm.get("trust_remote_code", False)), "--trust-remote-code")
    bool_flag(command, bool(vllm.get("enable_auto_tool_choice", False)), "--enable-auto-tool-choice")
    bool_flag(command, bool(vllm.get("enable_prefix_caching", False)), "--enable-prefix-caching")
    bool_flag(command, bool(vllm.get("enable_chunked_prefill", False)), "--enable-chunked-prefill")
    bool_flag(command, bool(vllm.get("async_scheduling", False)), "--async-scheduling")
    bool_flag(command, bool(vllm.get("disable_log_stats", False)), "--disable-log-stats")

    append_engine_args(command, vllm.get("engine_args", {}) or {})

    for arg in vllm.get("extra_args", []) or []:
        command.append(str(arg))

    if wrap_startup:
        return wrap_with_startup_mods(command, model.get("startup_mods", []))
    return command


def launch_port_mapping(stack: dict[str, Any], model: dict[str, Any]) -> str:
    routing = model["routing"]
    bind_ip = stack["network"]["bind_ip"] if routing.get("expose_host", False) else "127.0.0.1"
    return f"{bind_ip}:{routing['host_port']}:{routing.get('internal_port', 8000)}"


def launch_extra_docker_args(stack: dict[str, Any], model: dict[str, Any]) -> str:
    visible_devices = ",".join(str(device_id) for device_id in model["gpu"]["device_ids"])
    args = [
        "--env-file",
        f"{stack['deploy_dir']}/.env",
        "-e",
        "HF_HOME=/root/.cache/huggingface",
        "-e",
        f"CUDA_VISIBLE_DEVICES={visible_devices}",
        "-e",
        f"NVIDIA_VISIBLE_DEVICES={visible_devices}",
        "--network",
        stack["network"]["name"],
        "--network-alias",
        model["container_name"],
    ]
    for key, value in (model.get("env") or {}).items():
        args.extend(["-e", f"{key}={value}"])
    return " ".join(str(arg) for arg in args)


def render_vllm_launch_script(model: dict[str, Any]) -> str:
    recipe = model.get("launch_recipe")
    lines = [
        "#!/bin/bash",
        "set -euo pipefail",
        GENERATED_HEADER,
    ]
    if recipe:
        lines.append(f"# Recipe reference: {recipe}")
    lines.extend(["", f"exec {shlex.join(model['launch_command'])}", ""])
    return "\n".join(lines)


def render_vllm_launch_manifest(models: list[dict[str, Any]]) -> str:
    data = {
        "vllm_launch_models": [
            {
                "id": model["id"],
                "container_name": model["container_name"],
                "image": model["launch_image"],
                "launch_script": model["launch_script"],
                "recipe": model.get("launch_recipe"),
                "port_mapping": model["launch_port_mapping"],
                "internal_port": model["routing"].get("internal_port", 8000),
                "extra_docker_args": model["launch_extra_docker_args"],
                "apply_mods": [mod["host_path"] for mod in model.get("startup_mods", [])],
            }
            for model in models
        ]
    }
    return GENERATED_HEADER + "\n" + yaml.safe_dump(data, sort_keys=False)


def normalize_model(model: dict[str, Any]) -> dict[str, Any]:
    normalized = model.copy()
    normalized["kind"] = str(normalized.get("kind", "chat"))
    normalized["vllm"] = dict(normalized.get("vllm") or {})
    normalized["startup_mods"] = normalize_startup_mods(normalized["vllm"])
    litellm = dict(normalized.get("litellm") or {})
    litellm.setdefault("mode", normalized["kind"])
    normalized["litellm"] = litellm
    return normalized


def enrich(stack: dict[str, Any], models_doc: dict[str, Any]) -> dict[str, Any]:
    enabled = [
        normalize_model(m) for m in models_doc.get("models", []) if bool(m.get("enabled", True))
    ]
    first_chat_model = ""
    for model in enabled:
        model["container_name"] = f"vllm-{model['id']}"
        model["launch_image"] = model.get("image", stack["images"]["vllm_default"])
        model["command"] = build_vllm_command(model)
        model["launch_command"] = build_vllm_command(model, wrap_startup=False)
        model["launch_script"] = f"vllm-launch/{model['id']}.sh"
        model["launch_recipe"] = model["vllm"].get("recipe")
        model["launch_port_mapping"] = launch_port_mapping(stack, model)
        model["launch_extra_docker_args"] = launch_extra_docker_args(stack, model)
        model["metrics_target"] = (
            f"{model['container_name']}:{model.get('routing', {}).get('internal_port', 8000)}"
        )
        if not first_chat_model and model.get("kind") == "chat":
            first_chat_model = str((model.get("served_names") or [""])[0])

    return {
        "stack": stack,
        "models": enabled,
        "first_chat_model": first_chat_model,
        "header": GENERATED_HEADER,
    }


def render_template(env: Environment, name: str, context: dict[str, Any]) -> str:
    return env.get_template(name).render(**context).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--stack", default=ROOT / "stack.yml", type=Path)
    parser.add_argument("--models", default=ROOT / "models.yml", type=Path)
    args = parser.parse_args()

    stack = load_yaml(args.stack)
    models_doc = load_yaml(args.models)
    validate(stack, models_doc, ROOT)

    env = Environment(
        loader=FileSystemLoader(ROOT / "templates"),
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    env.filters["yaml"] = dump_yaml
    env.filters["json"] = to_json

    context = enrich(stack, models_doc)
    outputs = {
        ROOT / "generated/docker-compose.generated.yml": "docker-compose.generated.yml.j2",
        ROOT / "generated/litellm.config.yaml": "litellm.config.yaml.j2",
        ROOT / "generated/prometheus-vllm-targets.yml": "prometheus-vllm-targets.yml.j2",
    }

    changed: list[str] = []
    for path, template_name in outputs.items():
        content = render_template(env, template_name, context)
        if write_if_changed(path, content):
            changed.append(str(path.relative_to(ROOT)))

    manifest_path = ROOT / "generated/vllm-launch.generated.yml"
    manifest_content = render_vllm_launch_manifest(context["models"])
    if write_if_changed(manifest_path, manifest_content):
        changed.append(str(manifest_path.relative_to(ROOT)))

    GENERATED_VLLM_LAUNCH_DIR.mkdir(parents=True, exist_ok=True)
    expected_scripts = set()
    for model in context["models"]:
        script_path = ROOT / "generated" / model["launch_script"]
        expected_scripts.add(script_path)
        if write_if_changed(script_path, render_vllm_launch_script(model)):
            changed.append(str(script_path.relative_to(ROOT)))
        script_path.chmod(0o755)
    for script_path in GENERATED_VLLM_LAUNCH_DIR.glob("*.sh"):
        if script_path not in expected_scripts:
            script_path.unlink()
            changed.append(str(script_path.relative_to(ROOT)))

    if changed:
        print("changed:")
        for path in changed:
            print(f"  {path}")
    else:
        print("generated files already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
