#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined

from validate_models import ROOT, load_yaml, validate


GENERATED_HEADER = "# DO NOT EDIT: generated by scripts/render.py from stack.yml and models.yml"


def write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def dump_yaml(value: Any, indent: int = 0) -> str:
    text = yaml.safe_dump(value, sort_keys=False, default_flow_style=False).rstrip()
    if indent:
        prefix = " " * indent
        text = "\n".join(prefix + line if line else line for line in text.splitlines())
    return text


def to_json(value: Any) -> str:
    return json.dumps(value)


def remote_chat_template(path: str) -> str:
    return "/workspace/vllm/" + path


def bool_flag(command: list[str], enabled: bool, flag: str) -> None:
    if enabled:
        command.append(flag)


def value_flag(command: list[str], value: Any, flag: str) -> None:
    if value is not None:
        command.extend([flag, str(value)])


def build_vllm_command(model: dict[str, Any]) -> list[str]:
    routing = model["routing"]
    gpu = model["gpu"]
    vllm = model.get("vllm", {})

    command = [
        "vllm",
        "serve",
        str(model["hf_model"]),
        "--host",
        "0.0.0.0",
        "--port",
        str(routing.get("internal_port", 8000)),
        "--gpu-memory-utilization",
        str(gpu["memory_fraction"]),
    ]

    served_names = model.get("served_names") or []
    if served_names:
        command.append("--served-model-name")
        command.extend(str(name) for name in served_names)

    value_flag(command, vllm.get("max_model_len"), "--max-model-len")
    value_flag(command, vllm.get("max_num_seqs"), "--max-num-seqs")
    value_flag(command, vllm.get("max_num_batched_tokens"), "--max-num-batched-tokens")
    value_flag(command, vllm.get("tensor_parallel_size"), "--tensor-parallel-size")
    value_flag(command, vllm.get("dtype"), "--dtype")
    value_flag(command, vllm.get("kv_cache_dtype"), "--kv-cache-dtype")
    value_flag(command, vllm.get("kv_cache_memory_bytes"), "--kv-cache-memory-bytes")
    value_flag(command, vllm.get("quantization"), "--quantization")
    value_flag(command, vllm.get("tool_call_parser"), "--tool-call-parser")
    value_flag(command, vllm.get("reasoning_parser"), "--reasoning-parser")

    chat_template = vllm.get("chat_template")
    if chat_template:
        value_flag(command, remote_chat_template(str(chat_template)), "--chat-template")

    bool_flag(command, bool(vllm.get("trust_remote_code", False)), "--trust-remote-code")
    bool_flag(command, bool(vllm.get("enable_auto_tool_choice", False)), "--enable-auto-tool-choice")
    bool_flag(command, bool(vllm.get("enable_prefix_caching", False)), "--enable-prefix-caching")
    bool_flag(command, bool(vllm.get("disable_log_stats", False)), "--disable-log-stats")

    for arg in vllm.get("extra_args", []) or []:
        command.append(str(arg))

    return command


def enrich(stack: dict[str, Any], models_doc: dict[str, Any]) -> dict[str, Any]:
    enabled = [m.copy() for m in models_doc.get("models", []) if bool(m.get("enabled", True))]
    first_chat_model = ""
    for model in enabled:
        model["container_name"] = f"vllm-{model['id']}"
        model["command"] = build_vllm_command(model)
        model["metrics_target"] = (
            f"{model['container_name']}:{model.get('routing', {}).get('internal_port', 8000)}"
        )
        if not first_chat_model and model.get("kind") == "chat":
            first_chat_model = str((model.get("served_names") or [""])[0])

    return {
        "stack": stack,
        "models": enabled,
        "first_chat_model": first_chat_model,
        "header": GENERATED_HEADER,
    }


def render_template(env: Environment, name: str, context: dict[str, Any]) -> str:
    return env.get_template(name).render(**context).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--stack", default=ROOT / "stack.yml", type=Path)
    parser.add_argument("--models", default=ROOT / "models.yml", type=Path)
    args = parser.parse_args()

    stack = load_yaml(args.stack)
    models_doc = load_yaml(args.models)
    validate(stack, models_doc, ROOT)

    env = Environment(
        loader=FileSystemLoader(ROOT / "templates"),
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    env.filters["yaml"] = dump_yaml
    env.filters["json"] = to_json

    context = enrich(stack, models_doc)
    outputs = {
        ROOT / "generated/docker-compose.generated.yml": "docker-compose.generated.yml.j2",
        ROOT / "generated/litellm.config.yaml": "litellm.config.yaml.j2",
        ROOT / "generated/prometheus-vllm-targets.yml": "prometheus-vllm-targets.yml.j2",
        ROOT / "generated/traefik-dynamic.yml": "traefik-dynamic.yml.j2",
    }

    changed: list[str] = []
    for path, template_name in outputs.items():
        content = render_template(env, template_name, context)
        if write_if_changed(path, content):
            changed.append(str(path.relative_to(ROOT)))

    if changed:
        print("changed:")
        for path in changed:
            print(f"  {path}")
    else:
        print("generated files already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
